server:
  port: 8888

spring:
  application:
    name: Gateway

  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true