server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: Gateway
    gateway:
      discovery:
        locator:
          enabled: true # Enables dynamic route discovery from Consul
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
