spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true